# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.

name: 🔖 Labeler

on: [pull_request_target] # zizmor: ignore[dangerous-triggers]

permissions:
  contents: read
  pull-requests: write

jobs:
  label:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/labeler
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
