on:
  workflow_call:
    inputs:
      run-on-windows:
        required: false
        type: boolean
        default: false

permissions: {}

jobs:
  test:
    name: 🧪 Tests
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - ${{ inputs.run-on-windows && 'windows-latest' || '' }}
        exclude:
          - os: ""

    runs-on: ${{ matrix.os }}

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4.2.2
        with:
          persist-credentials: false
          sparse-checkout-cone-mode: false
          # Download only the necessary files
          sparse-checkout: |
            src
            tests
            package.json
            bun.lock
            bunfig.toml
            bunup.config.ts
            tsconfig*.json
            !**/*.md

      - name: 🔧 Setup Bun
        uses: oven-sh/setup-bun@v2.0.2

      # Run only on Windows because on Linux there are no problems with slow package installation
      - name: 📥 Cache Bun dependencies (Windows)
        if: runner.os == 'Windows'
        uses: actions/cache@v4.2.3
        with:
          path: ~\.bun
          key: ${{ matrix.os }}-bun-${{ hashFiles('**/bun.lock') }}
          restore-keys: ${{ matrix.os }}-bun-cache-

      - name: 📦 Install dependencies
        run: bun install --production --frozen-lockfile --prefer-offline --ignore-scripts --omit=optional

      - name: 🧪 Run tests
        run: bun run test
