on: [workflow_call]

permissions: {}

env:
  WINDOWS_USERPROFILE: 'D:'

jobs:
  test:
    name: 🧪 Tests
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      # https://ichard26.github.io/blog/2025/03/faster-pip-ci-on-windows-d-drive/#moving-temp-to-the-d-drive
      - name: 🗂️ Set temp dir on Windows
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          $TEMP_DIR = "$env:WINDOWS_USERPROFILE\Temp"
          # Create temp dir
          New-Item -ItemType Directory -Force -Path $TEMP_DIR | Out-Null

          "TEMP=$TEMP_DIR"  >> $env:GITHUB_ENV
          "TMP=$TEMP_DIR"   >> $env:GITHUB_ENV

      - name: 🔓 Disable Windows Defender
        if: runner.os == 'Windows'
        shell: powershell
        run: Set-MpPreference -DisableRealtimeMonitoring $true

      - name: 🛜 Network tweaks for Windows
        if: runner.os == 'Windows'
        shell: powershell
        run: |
          # Use Google DNS (https://github.com/oven-sh/bun/issues/4066#issuecomment-1777701194)
          Get-NetAdapter | ForEach-Object { Set-DnsClientServerAddress -InterfaceIndex $_.InterfaceIndex -ServerAddresses ("8.8.8.8", "8.8.4.4") }

          # Disable IPv6 (https://github.com/oven-sh/bun/issues/4938#issuecomment-1720172113)
          Get-NetAdapterBinding -ComponentID ms_tcpip6 | ForEach-Object { Disable-NetAdapterBinding -InterfaceAlias $_.Name -ComponentID ms_tcpip6 }

      - name: 📥 Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
          sparse-checkout-cone-mode: false
          # Download only the necessary files
          sparse-checkout: |
            src
            tests
            package.json
            bun.lock
            bunfig.toml
            tsup.config.ts
            tsconfig*.json
            !**/*.md

      - name: 🔧 Setup Bun
        uses: oven-sh/setup-bun@4bc047ad259df6fc24a6c9b0f9a0cb08cf17fbe5 # v2
        env:
          USERPROFILE: ${{ env.WINDOWS_USERPROFILE }}
        with:
          bun-version: latest

      - name: 📥 Cache Bun dependencies
        # Run only on Windows because on Linux there are no problems with slow package installation
        if: runner.os == 'Windows'
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4
        env:
          USERPROFILE: ${{ env.WINDOWS_USERPROFILE }}
        with:
          path: '${{ env.USERPROFILE }}\.bun'
          key: ${{ matrix.os }}-bun-${{ hashFiles('**/bun.lock') }}

      # The main bottleneck is here, `bun install` takes too long on Windows
      # @oven-sh Please fix this 🙏
      - name: 📦 Install dependencies
        run: bun install --frozen-lockfile

      - name: 🧪 Run tests
        run: bun run test
